### ISSUE TITLE
Using not deleted

### ISSUE THREAD

**Issue by Nerwosolek** [ajakubo1/CGMerger#3]
Duplicate using clause not deleted from output cs file.

**Comment by ajakubo1** [comment]
Is there any chance you can provide me with an example .zip file with the problematic structure so I can replicate it easily? Unless it's like something common. I didn't notice using clauses being duplicated in the example I think (although - to tell you the truth - I didn't test it out with two separate .cs files, I just assumed it works exactly as it does on a python project).

Do remember that this file for C# settings https://github.com/ajakubo1/CGMerger/blob/main/templates/default-csharp/cgmerger.conf is quite important. especially this part, that is matching those using lines:

``exclude_line_regex = ^using``

or by manually running ``cgmerge.py --exclude-line-regex ^using``

**Comment by ajakubo1** [comment]
Ok, so we analyzed with @Nerwosolek the situation a bit and it turns out that the whole problem is that I open the file without specified encryption and visual studio is adding to all of the files something called ``BOM`` https://en.wikipedia.org/wiki/Byte_order_mark - which is completely screwing with the regex (first ``using`` is not filtered out). I already have a fix for it and I will create a PR and merge it in a sec.

**Comment by ajakubo1** [comment]
@Nerwosolek - can you confirm that my fix works?

pull the latest changes (lookout though, the templates are gone - I will create another repo for them) and run ``pip3 install <cgmerger folder>``. You will be then able to use the command locally from command line. Just run ``cgmerger`` in terminal.
